package io.bootique.lm.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.bootique.lm.cayenne.SDomain;
import io.bootique.lm.cayenne.STag;

/**
 * Class _SArticle was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SArticle extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BODY = Property.create("body", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<SDomain> DOMAIN = Property.create("domain", SDomain.class);
    public static final Property<List<STag>> S_TAGS = Property.create("sTags", List.class);

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setDomain(SDomain domain) {
        setToOneTarget("domain", domain, true);
    }

    public SDomain getDomain() {
        return (SDomain)readProperty("domain");
    }


    public void addToSTags(STag obj) {
        addToManyTarget("sTags", obj, true);
    }
    public void removeFromSTags(STag obj) {
        removeToManyTarget("sTags", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<STag> getSTags() {
        return (List<STag>)readProperty("sTags");
    }


}
